### ISSUE TITLE
usopp.is.devgenius.page 요청합니다.

### ISSUE THREAD

**Issue by ghdl023** [devgeniuspage/devgenius.page#11]
요청해요~~

**Comment by jams777** [comment]
https://github.com/devgeniuspage/usopp.is.devgenius.page.git 레파지토리가 생성되었습니다.

@ghdl023 님을 해당 레파지토리의 관리자로 초대해드렸습니다.

https://usopp.is.devgenius.page/

"우솝은 천재개발자다" 페이지가 생성되었습니다.

**Comment by jams777** [comment]
@all-contributors bot please add @ghdl023 for design

**Comment by jams777** [comment]
https://github.com/ghdl023/usopp.me

여기 내용을 

https://github.com/devgeniuspage/usopp.is.devgenius.page

여기로 옮기시면 

홈페이지가 잘 나올것 같습니다.
