### ISSUE TITLE
vincent.is.devgenius.page 요청드립니다.

### ISSUE THREAD

**Issue by vincent-jh** [devgeniuspage/devgenius.page#2]

**Comment by jams777** [comment]
vincent.is.devgenius.page 레파지토리가 생성되었습니다.

https://vincent.is.devgenius.page/ 로 접속가능합니다.

**Comment by vincent-jh** [comment]
감사합니다!

**Comment by jams777** [comment]
@all-contributors please add @Moongdol for design, code, ideas, promotion

**Comment by jams777** [comment]
@all-contributors please add @Moongdol for design, ideas

**Comment by jams777** [comment]
@all-contributors please add @Moongdol for design, ideas

**Comment by jams777** [comment]
@all-contributors please add @Moongdol for design, ideas
