### ISSUE TITLE
cheoninjeong.is.devgenius.page 요청드립니다.

### ISSUE THREAD

**Issue by CheonInJeong** [devgeniuspage/devgenius.page#8]
cheoninjeong.is.devgenius.page 요청드립니다.😆

**Comment by jams777** [comment]
cheoninjeong.is.devgenius.page 레파지토리가 생성되었습니다.
해당 레파지토리의 관리자로 할당되었습니다.

https://cheoninjeong.is.devgenius.page/ 로 접속 가능합니다.

**Comment by jams777** [comment]
"천인정은 천재개발자입니다"  페이지가 개설되었습니다.

**Comment by jams777** [comment]
@all-contributors bot please add @CheonInJeong for design
